// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResXTools.Extension
{
    internal sealed partial class Vsix
    {
        public const string Id = "ResXTools.489848e9-02ee-47dd-b03f-32131d73742a";
        public const string Name = "ResX Tools";
        public const string Description = @"A collection of tools that make working with resources easier and more efficient.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Enej Simrajh";
        public const string Tags = "";
    }
}
