// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResXTools.Extension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ResXToolsString = "a40247f9-ab1f-4e9d-bdca-f43f0cf99625";
        public static Guid ResXTools = new Guid(ResXToolsString);

        public const string UIContextString = "711a8b49-245d-4f07-841f-cb688890dbca";
        public static Guid UIContext = new Guid(UIContextString);

        public const string ResXDesignerGeneratorsCmdSetString = "84d2aa3b-aff2-4efa-b50d-b221930f91ae";
        public static Guid ResXDesignerGeneratorsCmdSet = new Guid(ResXDesignerGeneratorsCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SubMenuGroup = 0x1020;
        public const int CommandGroup = 0x1021;
        public const int SubMenu = 0x0100;
        public const int ApplyStaticGeneratorCommand = 0x0101;
        public const int ApplyServiceGeneratorCommand = 0x0102;
    }
}